apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
spec:
  accessModes:
  {{- toYaml .Values.persistentVolumeClaim.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.resources.requests.storage }}

